default_context:
  project_name: 'NLP App'
  project_slug: 'nlp-app'
  domain_main: 'nlp-app.com'
  domain_staging: 'stag.nlp-app.com'
  docker_swarm_stack_name_main: 'nlp-app-com'
  docker_swarm_stack_name_staging: 'stag-nlp-app-com'
  secret_key: '2ddd6f226035370c556eb7e66afecaf6b6f47d42dd08e32d364d426fa175bd89'
  first_superuser: 'admin@nlp-app.com'
  first_superuser_password: 'admin'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.nlp-app.com", "https://stag.nlp-app.com", "https://nlp-app.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@nlp-app.com'
  postgres_password: 'admin'
  pgadmin_default_user: 'admin@nlp-app.com'
  pgadmin_default_user_password: 'admin'
  traefik_constraint_tag: 'nlp-app.com'
  traefik_constraint_tag_staging: 'stag.nlp-app.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:admin'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
